### PR TITLE
Add data option

### PR DESCRIPTION
**Pull request by TonyMay71**
Hi Roland,

here is a pull request for the data option I would like to add to ElkWifi. It supports reading the status of the WLED controller but could be useful for any generic HTTP GET requests. I want to keep the data in the paged RAM so that I do not have to worry about allocating buffers in the normal Electron RAM and also to leave space for writing a controller program.

I have programmed my ElkWifi with this code, although development was done using sideways RAM. I have only tested that the data option works. If you have any tests you would like me to run, then please tell me what they are?

Please let me know what you think?

### CODE REVIEW

**Comment by AtomicRoland** [comment]
Hello Tony,

I will check your request next week.  I am quite busy at the moment.  

Best regards,
Roland 

-------------------------------------------------------------

**Comment by TonyMay71** [comment]
Hi Roland,

I have updated the error handling software as I wanted to catch connect errors in BASIC using ON ERROR, but it wasn't working. This seems to be due to undocumented behaviour of BASIC's error handler with error codes equal to zero. Setting a positive value for the error code resolved the issue.

Let me know when you are happy with the changes in principle and I will update the documentation. We can then work through any details before completing the merge.

Best Regards,

Tony

**Comment by AtomicRoland** [comment]
Added Tony May's enhancements and bug fixes

**Comment by AtomicRoland** [comment]
Added data option from Tony May.

**Pull request merged**
